import type { ManualEntry } from "@/lib/types";
import { LAYER_NAMES } from "@/lib/manual/layers";

// Why this exists:
// A returning user's Manual can grow to dozens of entries. Shipping every
// entry's full content in every turn's system prompt burns context and dilutes
// the model's attention on the current conversation. Recent entries still need
// to be fresh in Jove's mind — they were just written or refined. Older
// entries only need to be recognizable: Jove should know the shape of what's
// already in the Manual so it doesn't propose a duplicate or miss a
// connection, but it does not need to re-read the prose every turn.
//
// The compression scheme:
//   Recent (current or previous session) → full content, verbatim.
//   Older (everything else)               → one-line summary with key words.
//
// summary and key_words are generated by the composition Sonnet call at
// checkpoint-confirm time (see confirm-checkpoint.ts) and stored on the
// manual_entries row. Entries from before this feature shipped fall back to
// deriving a summary from the first sentence of content.

const RECENT_FULL_LIMIT = 4;

// Alias kept for callers that import this name; ManualEntry already includes
// the source_conversation_id field this file relies on.
export type ManualEntryForContext = ManualEntry;

/**
 * Render an entry in compressed form. Used for older entries that no longer
 * need to appear verbatim. Keeps the headline + one sentence + keywords so
 * Jove can still recognize and reference the entry without the full narrative.
 */
export function compressManualEntry(entry: ManualEntryForContext): string {
  const layerLabel = LAYER_NAMES[entry.layer] || `Layer ${entry.layer}`;
  const headline = entry.name ? `"${entry.name}"` : "(unnamed)";
  const summary = entry.summary?.trim() || deriveSummaryFromContent(entry.content);
  const keyWords =
    Array.isArray(entry.key_words) && entry.key_words.length > 0
      ? ` Key words: ${entry.key_words.join(", ")}.`
      : "";
  return `[Layer ${entry.layer} — ${layerLabel}] ${headline} — ${summary}${keyWords}`;
}

/**
 * Split-form output of the Manual context. `older` is byte-stable across a
 * session unless a new entry is confirmed — that makes it cacheable inside
 * the Jove static prompt prefix. `recent` changes every turn that adds a
 * new confirmation, so it stays in the dynamic (uncached) tail of the
 * prompt.
 *
 * Each string is either empty (no entries of that kind) or a complete
 * block ready to inline into a system prompt. Concatenating them in
 * `older + recent` order would not reproduce the legacy
 * `prepareManualContext` shape — see that function for the merged form
 * preserved for the buildSystemPrompt wrapper path.
 */
export interface ManualContextBlocks {
  /** "EARLIER ENTRIES …" header + one compressed line per older entry.
   *  Empty string when there are no older entries. */
  older: string;
  /** "CONFIRMED MANUAL" header + verbatim recent entries. Empty string
   *  when there are no recent entries. */
  recent: string;
}

/**
 * Build the split-form Manual context: a stable `older` block (cacheable)
 * and a `recent` block (current-session content, never cached).
 */
export function prepareManualContextBlocks(
  entries: ManualEntryForContext[],
  currentConversationId: string | null
): ManualContextBlocks {
  if (!entries.length) return { older: "", recent: "" };

  const { recent, older } = partitionEntries(entries, currentConversationId);

  let recentBlock = "";
  if (recent.length > 0) {
    recentBlock = "\nCONFIRMED MANUAL\n";
    for (const entry of recent) {
      recentBlock += `Layer ${entry.layer} (${LAYER_NAMES[entry.layer] || `Layer ${entry.layer}`})`;
      if (entry.name) recentBlock += ` — "${entry.name}"`;
      recentBlock += `:\n${entry.content}\n\n`;
    }
  }

  let olderBlock = "";
  if (older.length > 0) {
    olderBlock = "EARLIER ENTRIES (compressed — full content lives in the Manual):\n";
    for (const entry of older) {
      olderBlock += compressManualEntry(entry) + "\n";
    }
    olderBlock += "\n";
  }

  return { older: olderBlock, recent: recentBlock };
}

/**
 * Split entries into recent (rendered in full) and older (rendered compressed),
 * then concatenate into a single CONFIRMED MANUAL block ready to paste into
 * the system prompt. Entries authored in the current conversation — or, if
 * there are fewer than RECENT_FULL_LIMIT of those, the most recent entries
 * overall — stay verbatim. Everything else is compressed.
 *
 * Returning an empty string when the user has no entries so the caller can
 * omit the block entirely.
 *
 * Note: this preserves the legacy shape (CONFIRMED MANUAL header → recent
 * entries → EARLIER ENTRIES header → older entries). The cached-prompt
 * caller path uses `prepareManualContextBlocks` instead, which keeps the
 * two halves separate so the older block can sit inside the cached prefix.
 */
export function prepareManualContext(
  entries: ManualEntryForContext[],
  currentConversationId: string | null
): string {
  if (!entries.length) return "";

  const { recent, older } = prepareManualContextBlocks(
    entries,
    currentConversationId
  );

  // Recombine into legacy single-block shape. When recent is empty but older
  // exists, the legacy output still emitted the "\nCONFIRMED MANUAL\n"
  // header before the EARLIER block — preserve that quirk by prepending it
  // when needed so existing callers see byte-identical output.
  if (!recent) {
    return older ? "\nCONFIRMED MANUAL\n" + older : "";
  }
  return recent + older;
}

function partitionEntries(
  entries: ManualEntryForContext[],
  currentConversationId: string | null
): { recent: ManualEntryForContext[]; older: ManualEntryForContext[] } {
  // First pass: anything authored in the current conversation is automatically
  // recent. This keeps freshly-confirmed entries in full so Jove can reference
  // them specifically without having to reach through compressed form.
  const currentSession = currentConversationId
    ? entries.filter((e) => e.source_conversation_id === currentConversationId)
    : [];

  const notCurrent = currentConversationId
    ? entries.filter((e) => e.source_conversation_id !== currentConversationId)
    : entries.slice();

  // If the current session didn't produce enough recent entries, backfill with
  // the most recent entries overall so Jove always sees at least a handful in
  // full. Sorting by created_at when present, otherwise preserving input
  // order.
  const sortedNotCurrent = [...notCurrent].sort(byCreatedAtDesc);
  const needed = Math.max(0, RECENT_FULL_LIMIT - currentSession.length);
  const backfill = sortedNotCurrent.slice(0, needed);
  const olderPool = sortedNotCurrent.slice(needed);

  // Recent list is rendered in chronological order (oldest-first) so the
  // narrative reads naturally top-to-bottom.
  const recent = [...currentSession, ...backfill].sort(byCreatedAtAsc);

  return { recent, older: olderPool };
}

function byCreatedAtAsc(a: ManualEntryForContext, b: ManualEntryForContext): number {
  const ta = a.created_at ? Date.parse(a.created_at) : 0;
  const tb = b.created_at ? Date.parse(b.created_at) : 0;
  return ta - tb;
}

function byCreatedAtDesc(a: ManualEntryForContext, b: ManualEntryForContext): number {
  return byCreatedAtAsc(b, a);
}

/**
 * First-sentence fallback when an explicit summary is missing. Used here
 * for older entries from before the compressed-summary feature shipped,
 * and re-exported for confirm-checkpoint.ts to use when composition omits
 * a summary or when the user edits content in the review overlay.
 */
export function deriveSummaryFromContent(content: string): string {
  const firstSentence = content.split(/(?<=[.!?])\s+/)[0] || content;
  const trimmed = firstSentence.trim();
  if (trimmed.length <= 240) return trimmed;
  return trimmed.slice(0, 237).trimEnd() + "...";
}
