import type { ManualEntry } from "@/lib/types";
import { LAYER_NAMES } from "@/lib/manual/layers";

// Why this exists:
// A returning user's Manual can grow to dozens of entries. Shipping every
// entry's full content in every turn's system prompt burns context and dilutes
// the model's attention on the current conversation. Recent entries still need
// to be fresh in Jove's mind — they were just written or refined. Older
// entries only need to be recognizable: Jove should know the shape of what's
// already in the Manual so it doesn't propose a duplicate or miss a
// connection, but it does not need to re-read the prose every turn.
//
// The compression scheme:
//   Recent (current or previous session) → full content, verbatim.
//   Older (everything else)               → one-line summary with key words.
//
// summary and key_words are generated by the composition Sonnet call at
// checkpoint-confirm time (see confirm-checkpoint.ts) and stored on the
// manual_entries row. Entries from before this feature shipped fall back to
// deriving a summary from the first sentence of content.

const RECENT_FULL_LIMIT = 4;

export interface ManualEntryForContext extends ManualEntry {
  source_conversation_id?: string | null;
}

/**
 * Render an entry in compressed form. Used for older entries that no longer
 * need to appear verbatim. Keeps the headline + one sentence + keywords so
 * Jove can still recognize and reference the entry without the full narrative.
 */
export function compressManualEntry(entry: ManualEntryForContext): string {
  const layerLabel = LAYER_NAMES[entry.layer] || `Layer ${entry.layer}`;
  const headline = entry.name ? `"${entry.name}"` : "(unnamed)";
  const summary = entry.summary?.trim() || deriveSummaryFromContent(entry.content);
  const keyWords =
    Array.isArray(entry.key_words) && entry.key_words.length > 0
      ? ` Key words: ${entry.key_words.join(", ")}.`
      : "";
  return `[Layer ${entry.layer} — ${layerLabel}] ${headline} — ${summary}${keyWords}`;
}

/**
 * Split entries into recent (rendered in full) and older (rendered compressed),
 * then concatenate into a single CONFIRMED MANUAL block ready to paste into
 * the system prompt. Entries authored in the current conversation — or, if
 * there are fewer than RECENT_FULL_LIMIT of those, the most recent entries
 * overall — stay verbatim. Everything else is compressed.
 *
 * Returning an empty string when the user has no entries so the caller can
 * omit the block entirely.
 */
export function prepareManualContext(
  entries: ManualEntryForContext[],
  currentConversationId: string | null
): string {
  if (!entries.length) return "";

  const { recent, older } = partitionEntries(entries, currentConversationId);

  let block = "\nCONFIRMED MANUAL\n";

  if (recent.length > 0) {
    for (const entry of recent) {
      block += `Layer ${entry.layer} (${LAYER_NAMES[entry.layer] || `Layer ${entry.layer}`})`;
      if (entry.name) block += ` — "${entry.name}"`;
      block += `:\n${entry.content}\n\n`;
    }
  }

  if (older.length > 0) {
    block += "EARLIER ENTRIES (compressed — full content lives in the Manual):\n";
    for (const entry of older) {
      block += compressManualEntry(entry) + "\n";
    }
    block += "\n";
  }

  return block;
}

function partitionEntries(
  entries: ManualEntryForContext[],
  currentConversationId: string | null
): { recent: ManualEntryForContext[]; older: ManualEntryForContext[] } {
  // First pass: anything authored in the current conversation is automatically
  // recent. This keeps freshly-confirmed entries in full so Jove can reference
  // them specifically without having to reach through compressed form.
  const currentSession = currentConversationId
    ? entries.filter((e) => e.source_conversation_id === currentConversationId)
    : [];

  const notCurrent = currentConversationId
    ? entries.filter((e) => e.source_conversation_id !== currentConversationId)
    : entries.slice();

  // If the current session didn't produce enough recent entries, backfill with
  // the most recent entries overall so Jove always sees at least a handful in
  // full. Sorting by created_at when present, otherwise preserving input
  // order.
  const sortedNotCurrent = [...notCurrent].sort(byCreatedAtDesc);
  const needed = Math.max(0, RECENT_FULL_LIMIT - currentSession.length);
  const backfill = sortedNotCurrent.slice(0, needed);
  const olderPool = sortedNotCurrent.slice(needed);

  // Recent list is rendered in chronological order (oldest-first) so the
  // narrative reads naturally top-to-bottom.
  const recent = [...currentSession, ...backfill].sort(byCreatedAtAsc);

  return { recent, older: olderPool };
}

function byCreatedAtAsc(a: ManualEntryForContext, b: ManualEntryForContext): number {
  const ta = a.created_at ? Date.parse(a.created_at) : 0;
  const tb = b.created_at ? Date.parse(b.created_at) : 0;
  return ta - tb;
}

function byCreatedAtDesc(a: ManualEntryForContext, b: ManualEntryForContext): number {
  return byCreatedAtAsc(b, a);
}

function deriveSummaryFromContent(content: string): string {
  const firstSentence = content.split(/(?<=[.!?])\s+/)[0] || content;
  const trimmed = firstSentence.trim();
  if (trimmed.length <= 240) return trimmed;
  return trimmed.slice(0, 237).trimEnd() + "...";
}
